algo: dueling_dqn
backend: dp
batch_size: 32
env: PongNoFrameskip-v4
episode_length: 500
eps_end: 0.02
eps_last_frame: 150000
eps_start: 1.0
gamma: 0.99
gpus: 1
lr: 0.0001
max_episode_reward: 18
max_steps: 500000
n_steps: 4
replay_size: 100000
seed: 123
sync_rate: 1000
warm_start_size: 10000
warm_start_steps: 10000
